- name: Setting up desktop environment
  hosts: localhost
  tasks:
    - name: Installing ZSH
      become: yes
      apt:
        name:
          - zsh
          - git
   
    - name: Fetching oh-my-zsh
      uri:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        return_content: yes
      register: omz_install
   
    - name: Installing oh-my-zsh
      shell:
        cmd: sh
        stdin: '{{ omz_install.content }}'
   
    - name: Fetching oh-my-zsh configuration from git
      get_url:
        url: https://raw.githubusercontent.com/ramanverma2k/dotfiles/main/.zshrc
        dest: ~/

    - name: Installing oh-my-zsh plugins
      git:
        repo: 'https://github.com/zsh-users/{{ item }}'
        dest: ~/.oh-my-zsh/custom/plugins/{{ item }}
      loop:
        - zsh-autosuggestions
        - zsh-syntax-highlighting

    - name: Updating all packages
      become: yes
      apt:
        name: '*'
        state: latest
        update_cache: yes
