- name: Setting up Alacritty
  task:
    - name: Cloning alacritty
      git:
        repo: https://github.com/alacritty/alacritty
        dest: ~/setup/

    - name: Building alacritty
      shell: rustup override set stable && rustup update stable && cargo build --release
      args:
        chdir: ~/setup/alacritty

    - name: Configuring alacritty
      shell: '{{ item }}'
      loop:
        # ZSH
        - mkdir -p ${ZDOTDIR:-~}/.zsh_functions 
        - echo 'fpath+=${ZDOTDIR:-~}/.zsh_functions' >> ${ZDOTDIR:-~}/.zshrc
        - cp extra/completions/_alacritty ${ZDOTDIR:-~}/.zsh_functions/_alacritty
        # BASH
        - mkdir -p ~/.bash_completion
        - cp extra/completions/alacritty.bash ~/.bash_completion/alacritty
        - echo "source ~/.bash_completion/alacritty" >> ~/.bashrc
