- name: Fetch rustup
  uri:
    url: https://sh.rustup.rs
    return_content: yes
  register: rust_installer

- name: Run rustup installer
  shell:
    cmd: sh -s -- -y
    stdin: "{{ rust_installer.content }}"

- name: Refreshing shell to include rustup
  shell:
    cmd: source ~/.bashrc

- name: Cloning, Configuring & Installing BSPWM, Eww & Alacritty
  include_tasks: '{{ cosmetics }}'
  loop:
    - bspwm.yaml
    - alacritty.yaml
    - eww.yaml
  loop_control:
    loop_var: "cosmetics"

- name: Installing Rofi
  become: true
  dnf:
    name: rofi
    state: latest

- name: Editing BSPWMRC to include alacritty & rofi
  shell: '{{ item }}'
  args:
    chdir: ~/.config/sxhkd/
  loop:
    - grep -rl "urxvt" ./ | xargs sed -i "s/urxvt/alacritty/" 

- name: Setting up gdm
  become_user: true
  shell:
    cmd: sudo systemctl {{ item }}
  loop:
    - enable sddm
    - start sddm
    - set-default graphical.target