- name: Fetch rustup
  uri:
    url: https://sh.rustup.rs
    return_content: yes
  register: rust_installer

- name: Run rustup installer
  shell:
    cmd: sh -s -- -y
    stdin: "{{ rust_installer.content }}"
    
- name: Cloning dotfiles
  git:
    repo: https://github.com/ramanverma2k/dotfiles
    dest: ~/dotfiles

- name: Copying dotfiles
  shell:
    cmd: cp -r {{ item }} ~/.config/{{ item }}
    chdir: ~/dotfiles/
  loop:
    - bspwm
    - sxhkd
    - eww
    - wallpapers

- name: Cloning, Configuring & Installing BSPWM, Eww & Alacritty
  include_tasks: '{{ cosmetics }}'
  loop:
    - bspwm.yaml
    - alacritty.yaml
    - eww.yaml
  loop_control:
    loop_var: "cosmetics"

- name: Installing Rofi
  become: true
  dnf:
    name: rofi
    state: latest

- name: Setting up display manager
  become_user: true
  shell:
    cmd: sudo systemctl {{ item }}
  loop:
    - enable sddm.service
    - set-default graphical.target