- name: Cloning bspwm
  git:
    repo: https://github.com/baskerville/{{ item }}
    dest: ~/setup/{{ item }}
  loop:
    - bspwm
    - sxhkd

- name: Building bspwm
  become_user: yes
  shell: make && sudo make install
  args:
    chdir: ~/setup/bspwm

- name: Building sxhkd
  become_user: yes
  shell: make && sudo make install
  args:
    chdir: ~/setup/sxhkd

- name: Creating BSPWM & SXHKD directories in ~/.config
  file:
    path: ~/.config/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - bspwm
    - sxhkd

- name: Making bspwmrc executable & setting up autostart
  become_user: true
  shell:
    cmd: chmod u+x ~/.config/bspwm/bspwmrc && sudo cp stuff/bspwm.desktop /usr/share/xsessions/
    chdir: ~/scripts