- name: Cloning bspwm
  git:
    repo: https://github.com/baskerville/'{{ item }}'
    dest: ~/setup/
  loop:
    - bspwm
    - sxhkd

- name: Building bspwm
  become: yes
  shell: make && sudo make install
  args:
    chdir: ~/setup/bspw

- name: Building sxhkd
  become: yes
  shell: make && sudo make install
  args:
    chdir: ~/setup/sxhkd

- name: Creating BSPWM & SXHKD directories in ~/.config
  file:
    path: ~/.config/'{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - bspwm
    - sxhkd

- name: Configuring BSPWM
  command: cp /usr/local/share/doc/bspwm/examples/'{{ item }}'rc ~/.config/'{{ item }}'/''{{ item }}'rc
  loop:
    - bspwm
    - sxhkd
  shell: chmod u+x ~/.config/bspwm/bspwmrc && echo 'exec bspwmrc' > ~/.xinitrc