- name: Configuring git
  shell:
    cmd: git config --global {{ item }}
  loop:
    - user.name "ramanverma2k"
    - user.email "ramanverma4183@gmail.com" 
    - core.editor "nvim"

- name: Adding Docker to usergroup & enabling service
  become_user: yes
  shell:
    cmd: sudo {{ item }}
  loop:
    - usermod -aG docker $(whoami)
    - systemctl enable docker.service
    - systemctl enable containerd.service
    - systemctl start docker

- name: Setting up display manager
  become: true
  shell:
    cmd: sudo systemctl {{ item }}
  loop:
    - enable sddm.service
    - set-default graphical.target