- name: Cloning dotfiles
  git:
    repo: https://github.com/ramanverma2k/dotfiles
    dest: ~/dotfiles

- name: Creating .config directory
  file:
    path: ~/.config/
    state: directory
    mode: '0755'

- name: Copying dotfiles to ~/.config/
  shell:
    cmd: cp -r {{ item }} ~/.config/
    chdir: ~/dotfiles/
  loop:
    - bspwm
    - sxhkd
    - wallpapers
    - polybar
    - alacritty.yml

- name: Copying .zshrc from ~/dotfiles
  shell:
    cmd: cp .zshrc ~/
    chdir: ~/dotfiles

- name: Cloning sddm theme
  git:
    repo: https://github.com/catppuccin/sddm
    dest: ~/sddm

- name: Copying sddm theme
  become_user: true
  shell:
    cmd: sudo cp -r ./src/catpuccin-mocha /usr/share/sddm/themes/
    chdir: ~/sddm

- name: Updating sddm.conf
  become_user: true
  shell:
    cmd: sudo cp -r sddm.conf /etc/
    chdir: ~/dotfiles
