- name: Cloning dotfiles
  git:
    repo: https://github.com/ramanverma2k/dotfiles
    dest: ~/dotfiles

- name: Creating .config directory
  file:
    path: ~/.config/
    state: directory
    mode: '0755'

- name: Copying dotfiles to ~/.config/
  shell:
    cmd: cp -r {{ item }} ~/.config/
    chdir: ~/dotfiles/
  loop:
    - bspwm
    - sxhkd
    - wallpapers
    - polybar
    - alacritty.yml

- name: Copying .zshrc from ~/dotfiles
  shell:
    cmd: cp .zshrc ~/
    chdir: ~/dotfiles