- name: Cloning eww
  git:
    repo: https://github.com/elkowar/eww
    dest: ~/setup/

- name: Building eww
  shell: cargo build --release
  args:
    chdir: ~/setup/eww

- name: Configuring eww
  shell: chmod +x ./eww
  args:
    chdir: ~/setup/eww/target/release