- name: Cloning eww
  git:
    repo: https://github.com/elkowar/eww
    dest: ~/setup/eww

- name: Building eww
  shell:
    cmd: cargo build --release
    chdir: ~/setup/eww

- name: Configuring eww
  shell:
    cmd: chmod +x ./eww
    chdir: ~/setup/eww/target/release

- name: Copying eww to /usr/local/bin
  become_user: true
  shell:
    cmd: cp target/release/eww /usr/local/bin
    chdir: ~/setup/ewwc