---
- name: NerdFonts Playbook
  hosts: localhost
  tasks:
    - name: Checking if NerdFonts repo is available
      ansible.builtin.stat:
        path=/tmp/nerd-fonts
      register: fonts

    - name: Cloning NerdFonts
      ansible.builtin.command:
        cmd: "{{ ansible_env.SHELL }} -c \"{{ item }}\""
        chdir: /tmp/
        creates: "{{ ansible_env.HOME }}/.local/share/fonts/nerdfonts"
      loop:
        - git clone --filter=blob:none --sparse git@github.com:ryanoasis/nerd-fonts
        - cd nerd-fonts && git sparse-checkout add patched-fonts/JetBrainsMono
        - cd nerd-fonts && git sparse-checkout add patched-fonts/Noto
      when: not fonts.stat.exists

    - name: Installing Fonts
      ansible.builtin.command:
        cmd: "{{ ansible_env.SHELL }} -c \"./install.sh {{ item }}\""
        chdir: /tmp/nerd-fonts
      args:
        creates: "{{ ansible_env.HOME }}/.local/share/fonts/NerdFonts"
      changed_when: false
      loop:
        - JetBrainsMono
        - Noto

    - name: Cleaning up
      ansible.builtin.file:
        path: /tmp/nerd-fonts
        state: absent
