- name: Cloning NerdFonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts
    dest: ~/nerdfonts
    
- name: Installing NerdFonts
  shell:
    cmd: ./install.sh {{ item }}
    chdir: ~/nerdfonts
  loop:
    - JetBrainsMono
    - Noto