- name: Fetch rustup
  uri:
    url: https://sh.rustup.rs
    return_content: yes
  register: rust_installer

- name: Run rustup installer
  shell:
    cmd: sh -s -- -y
    stdin: "{{ rust_installer.content }}"

- name: Installing NVM
  shell:
    cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash

- name: Installing Nodejs
  shell:
    cmd: /usr/bin/zsh -ic 'nvm {{ item }}'
  loop:
    - install node
    - use node

- name: Installing golang
  become_user: true
  shell:
    cmd: "{{ item }}"
  loop:
    - curl -LO https://go.dev/dl/go1.19.4.linux-amd64.tar.gz
    - sudo rm -rf /usr/local/go
    - sudo tar -C /usr/local -xzf go1.19.4.linux-amd64.tar.gz

- name: Cloning Flutter/Dart Repository
  git:
    repo: https://github.com/flutter/flutter.git
    version: stable
    depth: 1
    dest: ~/.flutter