- name: Cloning Rofi
  git:
    repo: https://github.com/DaveDavenport/rofi
    dest: ~/setup/rofi

- name: Building rofi
  become_user: yes
  shell: {{ item }}
  args:
    chdir: ~/setup/rofi
  loop:
    - autoreconf -i
    - mkdir build
    - cd build
    - ../configure
    - make
    - make install

- name: Configuring eww
  shell: chmod +x ./eww
  args:
    chdir: ~/setup/eww/target/release