- name: Cloning Neovim
  git:
    repo: https://github.com/neovim/neovim
    dest: ./neovim
    depth: 1
    version: stable

- name: Building Neovim
  shell: make CMAKE_BUILD_TYPE=Release
  args:
    chdir: ./neovim/

- name: Installing Neovim
  become_user: yes
  shell:  make install
  args:
    chdir: ./neovim/

- name: Cloning Packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1

- name: Adding Docker to usergroup & enabling service
  become_user: yes
  shell:
    cmd: sudo {{ item }}
  loop:
    - usermod -aG docker $(whoami)
    - systemctl enable docker.service
    - systemctl enable containerd.service
    - systemctl start docker