---
- name: Rust Playbook
  hosts: localhost
  tasks:
    - name: Fetching rustup
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: 0755

    - name: Installing rust
      ansible.builtin.script: /tmp/rustup.sh -y
      args:
        creates: ~/.cargo && ~/.rustup
      register: install

    - name: Cleaning up
      ansible.builtin.file:
        path: /tmp/rustup.sh
        state: absent
      when: not install.failed
