---
- name: Rust Playbook
  hosts: localhost
  tasks:
    - name: Checking if rustup is installed
      ansible.builtin.stat:
        path="{{ ansible_env.HOME }}/.local/bin/rustup"
      register: rustup

    - name: Fetching rustup
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: 0755
      when: not rustup.stat.exists

    - name: Installing rust
      environment:
        CARGO_HOME: "{{ ansible_env.HOME }}/.local/bin/cargo"
        RUSTUP_HOME: "{{ ansible_env.HOME }}/.local/bin/rustup"
      ansible.builtin.script: /tmp/rustup.sh -y
      args:
        creates: "{{ ansible_env.HOME }}/.local/bin/cargo"
      register: install
      when: not rustup.stat.exists

    - name: Cleaning up
      ansible.builtin.file:
        path: /tmp/rustup.sh
        state: absent
      when: not install is skipped and not install is failed
