---
- name: Setting up Fedora
  hosts: localhost
  tasks:
    - name: Installing Development, Hardware, Printing, Multimedia, Fonts & Input method groups.
      become: true
      dnf:
        name:
        - '@C Development Tools and Libraries'
        - '@Development Tools'
        - '@Hardware Support'
        - '@Fonts'
        - '@Input Methods'
        - '@Multimedia'
        - '@Printing Support'
        state: latest

    - name: Installing dependencies for alacritty, bspwm, eww.
      become: true
      dnf:
        name:
          # BSPWM
          - libxcb
          - xcb-util
          - xcb-util-wm
          - xcb-util-keysyms
          - libxcb-devel
          - xcb-util-wm-devel
          - xcb-util-keysyms-devel
          - xcb-util-devel
          # Alacritty
          - cmake
          - freetype-devel
          - fontconfig-devel
          - libxcb-devel
          - libxkbcommon-devel
          - g++
          #eww
          - gtk3-devel
          - gtk-layer-shell-devel
          - pango-devel
          - gdk-pixbuf2-devel
          - cairo-devel
          - glib2-devel
          - glibc-devel
          #Neovim
          - ninja-build
        state: latest

    - name: Installing additional tools
      become: true
      dnf:
        name:
          - xrandr
          - feh
          - sddm
          - gh
          - rofi
          - fzf
          - ripgrep
          - firefox
          - thunar
          - gimp
        state: latest

    - name: Executing common playbooks
      include_tasks: ./common/{{ common }}
      loop:
        - configs.yaml
        - shell.yaml
        - languages.yaml
        - bspwm.yaml
        - alacritty.yaml
        - eww.yaml
        - fonts.yaml
        - tools.yaml
      loop_control:
        loop_var: "common"
        
    - name: Setting up Vlc Repository
      become: true
      shell:
        cmd: sudo dnf install {{ item }}
      loop:
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    - name: Installing VLC
      become: true
      dnf:
        name: vlc
        state: latest

    - name: Setting up VSCode Repository
      become: true
      shell:
        cmd: sudo {{ item }}
      loop:
        - rpm --import https://packages.microsoft.com/keys/microsoft.asc
        - sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

    - name: Installing VSCode
      become: true
      dnf:
        name: code
        state: latest

    - name: Setting up Docker Repository
      become: true
      shell:
        cmd: sudo dnf {{ item }}
      loop:
        - -y install dnf-plugins-core
        - config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    - name: Installing Docker
      become: true
      dnf:
        name:
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: Downloading & installing Only office
      become: true
      shell: 
        cmd: "{{ item }}"
      loop:
        - wget https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors.x86_64.rpm
        - sudo dnf install ./onlyoffice-desktopeditors.x86_64.rpm -y
        - rm -rf onlyoffice-desktopeditors.x86_64.rpm
    
    - name: Executing cleanup playbook
      include_tasks: ./common/cleanup.yaml