---
- name: Setting up Fedora
  hosts: localhost
  tasks:
    - name: Installing Development, Hardware, Printing, Multimedia, Fonts & Input method groups.
      become: true
      dnf:
        name:
        - zsh
        - git
        - '@C Development Tools and Libraries'
        - '@Development Tools'
        - '@Hardware Support'
        - '@Fonts'
        - '@Input Methods'
        - '@Multimedia'
        - '@Printing Support'
        state: latest

    - name: Installing dependencies for alacritty, bspwm, eww.
      become: true
      dnf:
        name:
          - sddm
          # BSPWM
          - libxcb
          - xcb-util
          - xcb-util-wm
          - xcb-util-keysyms
          - libxcb-devel
          - xcb-util-wm-devel
          - xcb-util-keysyms-devel
          - xcb-util-devel
          # Alacritty
          - cmake
          - freetype-devel
          - fontconfig-devel
          - libxcb-devel
          - libxkbcommon-devel
          - g++
          #eww
          - gtk3-devel
          - gtk-layer-shell-devel
          - pango-devel
          - gdk-pixbuf2-devel
          - cairo-devel
          - glib2-devel
          - glibc-devel
        state: latest

    - name: Installing base
      import_tasks:
        file: common/base.yaml