---
- name: Setting up Fedora
  hosts: localhost
  tasks:
    - name: Installing Development, Hardware, Printing, Multimedia, Fonts & Input method groups.
      become: true
      dnf:
        name:
        - '@C Development Tools and Libraries'
        - '@Development Tools'
        - '@Hardware Support'
        - '@Fonts'
        - '@Input Methods'
        - '@Multimedia'
        - '@Printing Support'
        state: latest

    - name: Installing dependencies for alacritty, bspwm, eww.
      become: true
      dnf:
        name:
          - xrandr
          - feh
          - sddm
          # BSPWM
          - libxcb
          - xcb-util
          - xcb-util-wm
          - xcb-util-keysyms
          - libxcb-devel
          - xcb-util-wm-devel
          - xcb-util-keysyms-devel
          - xcb-util-devel
          # Alacritty
          - cmake
          - freetype-devel
          - fontconfig-devel
          - libxcb-devel
          - libxkbcommon-devel
          - g++
          #eww
          - gtk3-devel
          - gtk-layer-shell-devel
          - pango-devel
          - gdk-pixbuf2-devel
          - cairo-devel
          - glib2-devel
          - glibc-devel
        state: latest

    - name: Installing base
      import_tasks:
        file: common/base.yaml
        
    - name: Fetch rustup
      uri:
        url: https://sh.rustup.rs
        return_content: yes
      register: rust_installer

    - name: Run rustup installer
      shell:
        cmd: sh -s -- -y
        stdin: "{{ rust_installer.content }}"
        
    - name: Cloning dotfiles
      git:
        repo: https://github.com/ramanverma2k/dotfiles
        dest: ~/dotfiles

    - name: Create .config directory
      file:
        path: ~/.config/
        state: directory
        mode: '0755'

    - name: Copying dotfiles
      shell:
        cmd: cp -r {{ item }} ~/.config/{{ item }}
        chdir: ~/dotfiles/
      loop:
        - bspwm
        - sxhkd
        - eww
        - wallpapers

    - name: Cloning, Configuring & Installing BSPWM, Eww & Alacritty
      include_tasks: '{{ cosmetics }}'
      loop:
        - bspwm.yaml
        - alacritty.yaml
        - eww.yaml
      loop_control:
        loop_var: "cosmetics"

    - name: Installing Rofi
      become: true
      dnf:
        name: rofi
        state: latest

    - name: Setting up display manager
      become: true
      shell:
        cmd: sudo systemctl {{ item }}
      loop:
        - enable sddm.service
        - set-default graphical.target