---
- name: Docker Playbook
  hosts: localhost
  tasks:
    - name: Registering OS ID
      ansible.builtin.command: "{{ ansible_env.SHELL }} -c \"grep '^ID=.*' /etc/os-release | sed 's/ID=//'\""
      register: os

    - name: Register current user
      ansible.builtin.command: whoami
      changed_when: false
      register: current_user

    - name: Setting up Docker Repository
      become: true
      ansible.builtin.command:
        cmd: sudo dnf {{ item }}
      loop:
        - install dnf-plugins-core
        - config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      changed_when: false
      when: os.stdout == "fedora"

    - name: Setting up docker repository key for ubuntu
      become: true
      ansible.builtin.command:
        cmd: "{{ ansible_env.SHELL }} -ic \"\
              sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              \""
      when: os.stdout == "ubuntu" or os.stdout == "pop"

    - name: Setting up docker repository for ubuntu
      become: true
      ansible.builtin.shell:
        cmd: "echo \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              "
      when: os.stdout == "ubuntu" or os.stdout == "pop"

    - name: Installing Docker dependencies for ubuntu
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      when: os.stdout == "ubuntu" or os.stdout == "pop"

    - name: Installing Docker dependencies for fedora
      become: true
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      when: os.stdout == "fedora"

    - name: Adding Docker to usergroup & enabling service
      become: true
      ansible.builtin.command:
        cmd: sudo {{ item }}
      loop:
        - usermod -aG docker {{ current_user.stdout }}
        - systemctl enable docker.service
        - systemctl enable containerd.service
        - systemctl start docker
      changed_when: false
